### ISSUE TITLE
Can't use nixorg/nix:circleci locally with CircleCI CLI

### ISSUE THREAD

**Issue by fizruk** [nix-community/docker-nix#12]
I am trying out `nixorg/nix:circleci` for Circle CI, locally on macOS, using `circleci` CLI tool.
However, it fails at the code checkout step with `/bin/sh: mkdir: command not found` error.

```
$ circleci build
```

```
====>> Spin up Environment
Build-agent version 0.0.5895-01cdb92 (2018-05-29T20:07:10+0000)
Starting container nixorg/nix:circleci
  using image nixorg/nix@sha256:f3fff0fca5b41722a7c41b88b0879accd6f314307eb408601c1caaa9c1b71e3d

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1533558734
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=nix
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:owner/repo.git
  CIRCLE_SHA1=dcb3199a9bf730c351918d8f2322301926bdccba
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1533558734
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/sh
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
/bin/sh: mkdir: command not found
Error: Exited with code 127
Step failed
Task failed
```

Circle CI config:

```yaml
# .circleci/config.yml
version: 2

jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - run:
          command: nix-build

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
```

**Comment by fizruk** [comment]
Not sure, what's going on, but if I replace `checkout` step with

```yaml
      - run:
          command: |
            /bin/sh -c 'mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project'
```

then it works.
